### ISSUE TITLE
Доработка класса Player

### ISSUE THREAD

**Issue by idma88** [Dev-DAA/PegSolitaire#13]
Добавить:
1. Возможность устанавливать начальный счёт
2. Изменение счёта в сторону увеличения и уменьшения счёта (отрицательное значение счёта не допускается)

**Comment by AlexSnare** [comment]
4c5c5cfb3f63f043b992b94334d2a47ec6255ef7

**Comment by AlexSnare** [comment]
aea9823c742cf7831078c6b29cba5b39f4e0eee8
